apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "other-cookie-factory"
  namespace: "default"
  labels:
    app: "other-cookie-factory"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "other-cookie-factory"
  template:
    metadata:
      labels:
        app: "other-cookie-factory"
    spec:
      containers:
        - name: "cookieapp"
          image: "cookieapp:v1"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"